### ISSUE TITLE
KeyError: u'USD_BCH'

### ISSUE THREAD

**Issue by TekMuzik** [BitBotFactory/poloniexlendingbot#447]
New Day...New Issues

My bot has been running fine on Bitfinex for 16 hours or so, and then today I had to close it to change a setting (gapbottom), and when I restart it I get -

2017-08-10 15:12:50 Error USD_BCH
Traceback (most recent call last):
  File "lendingbot.py", line 81, in <module>
    Lending.lend_all()
  File "/home/pi/Downloads/poloniexlendingbot-bit/modules/Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/pi/Downloads/poloniexlendingbot-bit/modules/Lending.py", line 429, in lend_cur
    raise msg
KeyError: u'USD_BCH'

Unhandled error, please open a Github issue so we can fix it!

Also tried changing gapbottom back to what it was before, to see if it was some weird bug, and itgives the same error with the setting back to how it was originally.

Any advice?

**Comment by TekMuzik** [comment]
Seems to be working now after letting it "rest" for an hour or so. Might still be something to look in to though?

**Comment by rnevet** [comment]
Seems like an error from Bitfinex side regarding this Pair, maybe a technical issue on their side.

**Comment by utdrmac** [comment]
Was this ever confirmed as exchange issue? I started getting this a couple hours ago.

**Comment by utdrmac** [comment]
Dug into this by adding a lot of debugging lines. Sensitive info was redacted.

```
Welcome to Lending Bot on BITFINEX
Starting WebServer at 10.10.10.202 on port 8001 with template www
Started WebServer, lendingbot status available at http://10.10.10.202:8001/lendingbot.html

Lending_balances:
{u'ETH': u'0.18856598', u'BCH': u'0.49927929'}

Currency usable: ETH

Attempting to create lend_offer: ETH | 0.06285533999999998762710617941 | 0.00007792
api.create_loan_offer: ETH | 0.06285534 | 2 | 0.00007792
signed_payload : {'X-BFX-PAYLOAD': 'eyJub25jZSI6ICIxNTiwgInJlcXVlc3QiODQ0MDgwMDAiLCAicGVyaW9kIjogMiwgImN1cnJlbmN5IjogIkVUSCIsICJhbW91bnQiOiAiMC4wNjI4NTUzNCJ9', 'X-BFX-APIKEY': 'dJtpVIg4TqU76utH', 'X-BFX-SIGNATURE': 'c6beafdb42f3a9b2e286557644acb6d05ad058e3c20'}
Exception: API Error 400: {"message":"Invalid offer: incorrect amount, minimum is 50 dollar or equivalent in ETH"}
2017-08-11 19:22:53 Error USD_ETH
Traceback (most recent call last):
  File "lendingbot.py", line 81, in <module>
    Lending.lend_all()
  File "/usr/src/bitfinex/modules/Lending.py", line 236, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 435, in lend_cur
    raise msg
KeyError: u'USD_ETH'
```

**Comment by utdrmac** [comment]
At current rates bot tried to offer ETH loan worth $19.80

**Comment by utdrmac** [comment]
```
                        cur_min = usd_min / float(self.return_ticker()['USD_'+currency]['lowestAsk'])
```

The call to self.return_ticker does not contain info on the current pair; in this case, USD_ETH.

**Comment by Evanito** [comment]
@utdrmac Has highlighted that this issue is caused by the bot not respecting exchange minimums.

**Comment by rnevet** [comment]
@utdrmac @Evanito , I think this should be fixed here:
https://github.com/BitBotFactory/poloniexlendingbot/blob/e0f42abbe50d5f5d7dbdca2d70c5af537aaeb4bf/modules/Lending.py#L420

**Comment by utdrmac** [comment]
Still having this issue. Haven't had a chance to debug more as I'm in Dublin, away from home. Will attempt more. Difficulty in debugging since it doesn't happen a lot of the time.

```
2017-08-14 18:30:02 Error USD_ETH
Traceback (most recent call last):
  File "lendingbot.py", line 81, in <module>
    Lending.lend_all()
  File "/usr/src/bitfinex/modules/Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 429, in lend_cur
    raise msg
KeyError: u'USD_ETH'

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by utdrmac** [comment]
Ok. I figured this out. Follow along...

The first line of the "main loop" is this:
`Data.update_conversion_rates(output_currency, json_output_enabled)`

That function's 3rd line calls this: `ticker_response = api.return_ticker()`

In `api.return_ticker()` (for Bittrex), this decision is made:
`if base in ['BTC', 'USD'] and (curr == 'BTC' or curr in self.usedCurrencies):`

At this point of the running code, `self.usedCurrencies` is empty. No code has ran that fetches which coins I'm actively lending. That is not a problem for Data.update_conversion_..., **BUT** because `api.return_ticker()` is cached for 60 seconds, any subsequent calls to return_ticker, say for creating/adjusting a loan price, will not find the data it needs. Therefore, we have the error this bug report is all about.

*phew* That was a PITA to figure out. Now, how to properly fix...

**Comment by rnevet** [comment]
So this isn't related to the minimum error?

**Comment by rnevet** [comment]
@utdrmac care to join Slack?

Anyway, on Poloniex we don't have caching, wonder why @mahiso added caching on Bitfinex.

**Comment by utdrmac** [comment]
@rnevet I'm in the telegram group. I'm Krixt.

**Comment by JCBauza** [comment]
Raised a bug but seems to be related to this one... just that the keyerror is a different one: KeyError: u'USD_OMG'

**Comment by utdrmac** [comment]
@JCBauza Can you close your new one? It's the same bug.

@rnevet I think I'll attempt to fix this one for sure with the v2 API after I get back home tomorrow.

**Comment by JCBauza** [comment]
#479 is closed now

**Comment by JCBauza** [comment]
is there a workaround in the meanwhile?

**Comment by utdrmac** [comment]
@JCBauza https://github.com/BitBotFactory/poloniexlendingbot/pull/463

**Comment by JCBauza** [comment]
I'm a n00b, how can I update my code to include that with ubuntu? git pull something something?

**Comment by JCBauza** [comment]
I guess there are only 4 lines I could edit manually, just for future reference what is the correct way to do it?

**Comment by utdrmac** [comment]
@JCBauza yes, if you are a git beginner, editing the lines manually would be easiest.

**Comment by utdrmac** [comment]
@rnevet I think this can be closed now that #499 was merged

**Comment by rnevet** [comment]
Make it so. (And hope for the best)
